<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-30T21:04:52 IST" name="Default suite" finished-at="2023-12-30T21:05:08 IST" duration-ms="16058">
    <groups>
    </groups>
    <test started-at="2023-12-30T21:04:52 IST" name="Default test" finished-at="2023-12-30T21:05:08 IST" duration-ms="16058">
      <class name="com.sevenrmartsupermarket.tests.ManageDeliveryBoyTest">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.sevenrmartsupermarket.tests.ManageDeliveryBoyTest@61322f9d]" started-at="2023-12-30T21:04:52 IST" name="launchBrowser" finished-at="2023-12-30T21:04:59 IST" duration-ms="6939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="verifyCreatingNewDeliveryBoy()[pri:0, instance:com.sevenrmartsupermarket.tests.ManageDeliveryBoyTest@61322f9d]" started-at="2023-12-30T21:04:59 IST" name="verifyCreatingNewDeliveryBoy" finished-at="2023-12-30T21:05:08 IST" duration-ms="8707" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Praveen, flat no 24, tower 3, pocket 2, Mayur vihar phase 3] but found [Praveen Singh]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Praveen, flat no 24, tower 3, pocket 2, Mayur vihar phase 3] but found [Praveen Singh]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.sevenrmartsupermarket.tests.ManageDeliveryBoyTest.verifyCreatingNewDeliveryBoy(ManageDeliveryBoyTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreatingNewDeliveryBoy -->
        <test-method is-config="true" signature="terminateSession(org.testng.ITestResult)[pri:0, instance:com.sevenrmartsupermarket.tests.ManageDeliveryBoyTest@61322f9d]" started-at="2023-12-30T21:05:08 IST" name="terminateSession" finished-at="2023-12-30T21:05:08 IST" duration-ms="294" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyCreatingNewDeliveryBoy status=FAILURE method=ManageDeliveryBoyTest.verifyCreatingNewDeliveryBoy()[pri:0, instance:com.sevenrmartsupermarket.tests.ManageDeliveryBoyTest@61322f9d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateSession -->
      </class> <!-- com.sevenrmartsupermarket.tests.ManageDeliveryBoyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
